// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootLayoutProvider from "@/components/RootLayoutProvider"; // ใช้ @/ ตาม tsconfig.json

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vcommlighting | Create Next App",
    description: "Generated by create next app",
};

// *** FIX 1: สร้าง String ของ Font Class Name ที่สมบูรณ์ ***
const fontClasses = `${geistSans.variable} ${geistMono.variable}`;
// ******************************************************

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* FIX 2: ส่ง Class Name ลงไปใน Provider 
        แต่เราจะกำหนด Class Name ที่ body ใน Provider แทน
      */}
            <body className="antialiased">
                <RootLayoutProvider fontClasses={fontClasses}>
                    {children}
                </RootLayoutProvider>
            </body>
        </html>
    );
}